### ISSUE TITLE
Not working properly on El Capitan

### ISSUE THREAD

**Issue by fossilet** [tekezo/ShowyEdge#4]
I just upgraded the OS, and it seems ShowyEdge is not working correctly on OS X El Capitan Beta. I hope it will work in the future. Thank you for this great tool.

**Comment by tekezo** [comment]
Thank you for feedback.
I'll confirm this issue soon.

**Comment by tekezo** [comment]
I cannot reproduce this issue.
Please tell me your using input source.

Note:
OS X 10.11 seems to sometimes forget Login Items.
If your issue is that ShowyEdge does not launch at login, please confirm your Login Items.
You can confirm by this way:
https://support.apple.com/kb/PH18881?locale=en_US

**Comment by fossilet** [comment]
I cannot reproduce it any longer, maybe after a restart.
