### ISSUE TITLE
Will not open on startup

### ISSUE THREAD

**Issue by Lavvrence** [tekezo/ShowyEdge#5]
Showyedge doesn't open on startup on my machine. Running the latest version of the OS.

**Comment by tekezo** [comment]
Please confirm ShowyEdge is in System Preferences > Users & Groups > Login Items.

![160118-0001](https://cloud.githubusercontent.com/assets/659178/12392890/aa1c467c-be35-11e5-9a8e-c931bbec0023.png)

If ShowyEdge exists in Login Items, did you press shift keys at login?
If you pressed shift keys at login, OS X ignores Login Items.

**Comment by Lavvrence** [comment]
Yes, it is under login items and I did not press shift.

**Comment by tekezo** [comment]
Thank you for confirmation.

I think the cause is either:

1. ShowyEdge really was not opened. (If so, it's not ShowyEdge issue. It's an issue of OS X.)
2. ShowyEdge was opened but crashed immediately.

Are there any User Diagnostic Reports of ShowyEdge?
You can confirm them in Console app.

**Comment by Lavvrence** [comment]
Sorry, I was wrong about SE not opening: it does open, but it does not work until I have opened its window manually. I discovered that this is only a problem with keyboards that have been made with Ukelele.

**Comment by tekezo** [comment]
I reproduced this issue.
It might be an issue of OS X.

The InputSourceID of created input source takes two forms randomly.

* org.sil.ukelele.keyboardlayout.ukelele.keylayout.Ukelele
* org.sil.ukelele.keyboardlayout.ukelele.ukelele

If your configuration is only for one form, ShowyEdge does not work when the InputSourceID is another form.
Please open ShowyEdge Preferences when ShowyEdge does not change the color, then add configuration for another InputSourceID form.

**Comment by Lavvrence** [comment]
That did it! Thank you so much.
