### ISSUE TITLE
Align colors horizontally

### ISSUE THREAD

**Issue by eugenesvk** [tekezo/ShowyEdge#6]
Since many country flags align their colors from top to bottom (e.g. in Germany top black, middle red, bottom yellow), would you please add an option for a similar alignment of your highlight colors instead of the current left-to-right alignment (which only French and Italians are ok with :))?

What I'm aiming for is basically a mini-version of the default flag indicator without the actual bar, which allows me to save an extra button-space in the precious menu bar real estate!
See an example of a German flag in the current version of ShowyEdge. This indicator is on top of Bartender, which houses all those extra buttons that used to be crammed into the menu bar. 
<img width="34" alt="showyedge de" src="https://cloud.githubusercontent.com/assets/12956286/13988990/7ed875cc-f11f-11e5-8f63-ecd6aefe1e5c.png">

This is great except for the fact that the colors are misaligned an should run from top to bottom instead of from left to right. I understand that from the original design standpoint (a wide thin bar on top) this alignment makes sense, but I find a little flag indicator tucked in some free space (another candidate is that lonely apple icon in the left corner, way too much free space wasted there) to be much better than a wide bar that spans the whole menu bar length.

**Comment by tekezo** [comment]
I've added "Colors layout orientation".

Please upgrade ShowyEdge to the latest beta version from ShowyEdge Preferences > Advanced > Check for beta updates.

![160326-0002](https://cloud.githubusercontent.com/assets/659178/14047175/76b7a73e-f2e9-11e5-9f6a-3535adbfad32.png)

**Comment by eugenesvk** [comment]
That was :zap: fast, thank you very much, to works perfectly!
